# -*- coding: utf-8 -*-
"""Pricescrape.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZfDhTcgFQ-ry_QpQppYkgZucB9gYF6UP
"""

!pip install yfinance

import yfinance as yf
import pandas as pd

# Define the cryptocurrency symbols
tickers = {
    'Ethereum': 'ETH-USD',
    'Cardano': 'ADA-USD',
    'Shiba Inu': 'SHIB-USD'
}

# Define the time period
start_date = '2024-01-01'
end_date = '2024-07-31'

# Create an empty DataFrame to store the data
all_data = pd.DataFrame()

# Loop through each ticker and download the data
for name, symbol in tickers.items():
    data = yf.download(symbol, start=start_date, end=end_date, interval='1d')
    data['Cryptocurrency'] = name
    all_data = pd.concat([all_data, data])

# Select the columns of interest (including High and Low)
final_data = all_data[['Cryptocurrency', 'Open', 'High', 'Low', 'Close', 'Volume']]
final_data['Movement'] = final_data['Close'] - final_data['Low']


final_data.to_excel('cryptocurrency_data.xlsx', index=True)

print("Data has been successfully exported to 'cryptocurrency_data.xlsx'.")

import yfinance as yf
import pandas as pd

# Define the cryptocurrencies and the timeframe
tickers = ['ETH-USD', 'SHIB-USD', 'ADA-USD']
start_date = '2024-01-01'
end_date = '2024-07-31'

# Create a dictionary to store dataframes
crypto_data = {}

# Fetch data for each cryptocurrency
for crypto in tickers:
    data = yf.download(crypto, start=start_date, end=end_date)
    crypto_data[crypto] = data

# Create a Pandas Excel writer using openpyxl as the engine
with pd.ExcelWriter('crypto_prices.xlsx', engine='openpyxl') as writer:
    for crypto, data in crypto_data.items():
        # Save each dataframe to a different sheet
        data.to_excel(writer, sheet_name=crypto.split('-')[0])

print("Data has been saved to crypto_prices.xlsx")